### ISSUE TITLE
nifty.tools issue

### ISSUE THREAD

**Issue by HernandoMV** [constantinpape/elf#28] opened 2021-01-27 16:42 UTC
Error when importing nifty.tools, e.g:

```
from elf.transformation.affine import transform_coordinate

Traceback (most recent call last):
  File "/mnt/c/Users/herny/Documents/GitHub/Histology_to_ARA/tempCodeRunnerFile.py", line 1, in <module>
    from elf.transformation.affine import transform_coordinate
  File "/home/hmvergara/anaconda3/envs/imageanalysis/lib/python3.7/site-packages/elf-0.2.3-py3.7.egg/elf/transformation/__init__.py", line 1, in <module>
    from .affine import (compute_affine_matrix, scale_from_matrix, translation_from_matrix,
  File "/home/hmvergara/anaconda3/envs/imageanalysis/lib/python3.7/site-packages/elf-0.2.3-py3.7.egg/elf/transformation/affine.py", line 6, in <module>
    from .transform_impl import transform_subvolume
  File "/home/hmvergara/anaconda3/envs/imageanalysis/lib/python3.7/site-packages/elf-0.2.3-py3.7.egg/elf/transformation/transform_impl.py", line 5, in <module>
    import nifty.tools as nt
ModuleNotFoundError: No module named 'nifty.tools'
```

```
### Environment info:
 packages in environment at /home/hmvergara/anaconda3/envs/imageanalysis:

 Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
attrs                     19.3.0                     py_0
backcall                  0.1.0                    py37_0
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
brewer2mpl                1.4.1                    pypi_0    pypi
ca-certificates           2020.1.1                      0
certifi                   2019.11.28               py37_1
cycler                    0.10.0                   py37_0
dbus                      1.13.12              h746ee38_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
elf                       0.2.3                    pypi_0    pypi
entrypoints               0.3                      py37_0
expat                     2.2.6                he6710b0_0
flake8                    3.7.9                    py37_0
fontconfig                2.13.0               h9420a91_0
freetype                  2.9.1                h8a8886c_1
ggplot                    0.11.5                   pypi_0    pypi
glib                      2.63.1               h5a9c865_0
gmp                       6.1.2                h6c8ec71_1
gst-plugins-base          1.14.0               hbbd80ab_1
gstreamer                 1.14.0               hb453b48_1
icu                       58.2                 h9c2bf20_1
imageio                   2.9.0                    pypi_0    pypi
importlib_metadata        1.5.0                    py37_0
intel-openmp              2019.4                      243
ipykernel                 5.1.4            py37h39e3cac_0
ipython                   7.13.0           py37h5ca1d4c_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.5.1                      py_0
jedi                      0.16.0                   py37_1
jinja2                    2.11.1                     py_0
joblib                    0.14.1                   pypi_0    pypi
jpeg                      9b                   h024ee3a_2
jsonschema                3.2.0                    py37_0
jupyter                   1.0.0                    py37_7
jupyter_client            6.1.0                      py_0
jupyter_console           6.1.0                      py_0
jupyter_core              4.6.1                    py37_0
kiwisolver                1.1.0            py37he6710b0_0
ld_impl_linux-64          2.33.1               h53a641e_7
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libpng                    1.6.37               hbc83047_0
libsodium                 1.0.16               h1bed415_0
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.1.0                h2733197_0
libuuid                   1.0.3                h1bed415_2
libxcb                    1.13                 h1bed415_1
libxml2                   2.9.9                hea5a465_1
markupsafe                1.1.1            py37h7b6447c_0
matplotlib                3.1.3                    py37_0
matplotlib-base           3.1.3            py37hef1b27d_0
mccabe                    0.6.1                    py37_1
mistune                   0.8.4            py37h7b6447c_0
mkl                       2019.4                      243
mkl-service               2.3.0            py37he904b0f_0
mkl_fft                   1.0.15           py37ha843d7b_0
mkl_random                1.1.0            py37hd6b4f25_0
mock                      4.0.3                    pypi_0    pypi
mpld3                     0.3                      pypi_0    pypi
nbconvert                 5.6.1                    py37_0
nbformat                  5.0.4                      py_0
ncurses                   6.2                  he6710b0_0
networkx                  2.5                      pypi_0    pypi
nifty                     1.6.3                    pypi_0    pypi
notebook                  6.0.3                    py37_0
numpy                     1.17.2           py37haad9e8e_0
numpy-base                1.17.2           py37hde5b4d6_0
olefile                   0.46                     py37_0
openssl                   1.1.1e               h7b6447c_0
pandas                    1.0.3            py37h0573a6f_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
parso                     0.6.2                      py_0
patsy                     0.5.1                    py37_0
pcre                      8.43                 he6710b0_0
pexpect                   4.8.0                    py37_0
pickleshare               0.7.5                    py37_0
pillow                    6.2.0            py37h34e0f95_0
pip                       20.0.2                   py37_1
prometheus_client         0.7.1                      py_0
prompt_toolkit            3.0.3                      py_0
ptyprocess                0.6.0                    py37_0
pycodestyle               2.5.0                    py37_0
pyflakes                  2.1.1                    py37_0
pygments                  2.6.1                      py_0
pyparsing                 2.4.6                      py_0
pyqt                      5.9.2            py37h05f1152_2
pyrsistent                0.15.7           py37h7b6447c_0
python                    3.7.7           hcf32534_0_cpython
python-dateutil           2.8.1                      py_0
pytz                      2019.3                     py_0
pywavelets                1.1.1                    pypi_0    pypi
pyzmq                     18.1.1           py37he6710b0_0
qt                        5.9.7                h5867ecd_1
qtconsole                 4.7.2                      py_0
qtpy                      1.9.0                      py_0
readline                  8.0                  h7b6447c_0
scikit-image              0.18.1                   pypi_0    pypi
scikit-learn              0.22.2.post1             pypi_0    pypi
scipy                     1.4.1            py37h0b6359f_0
seaborn                   0.9.0                    py37_0
send2trash                1.5.0                    py37_0
setuptools                46.1.1                   py37_0
sip                       4.19.8           py37hf484d3e_0
six                       1.14.0                   py37_0
skan                      0.8                      pypi_0    pypi
sklearn                   0.0                      pypi_0    pypi
sqlite                    3.31.1               h7b6447c_0
statsmodels               0.11.0           py37h7b6447c_0
terminado                 0.8.3                    py37_0
testify                   0.11.0                   pypi_0    pypi
testpath                  0.4.4                      py_0
tifffile                  2021.1.14                pypi_0    pypi
tk                        8.6.8                hbc83047_0
tornado                   6.0.4            py37h7b6447c_1
traitlets                 4.3.3                    py37_0
wcwidth                   0.1.8                      py_0
webencodings              0.5.1                    py37_1
wheel                     0.34.2                   py37_0
widgetsnbextension        3.5.1                    py37_0
xz                        5.2.4                h14c3975_4
zeromq                    4.3.1                he6710b0_3
zipp                      2.2.0                      py_0
zlib                      1.2.11               h7b6447c_3
zstd                      1.3.7                h0b5b093_0
```

**Comment by constantinpape** [comment] 2021-01-27 17:42
Ok, the problem is that this is the wrong `nifty`; apparently there is a package on pypi called nifty.
The one we need is only available on conda and currently only on my channel, which makes it hard to install.
But there is a PR pending to add it to conda-forge (https://github.com/conda-forge/staged-recipes/pull/13770).
Once that is merged and it's available via conda-forge it should be much easier to set up the required env.

Until then we can just leave it with the workaround that you mentioned @HernandoMV and we can test proper installation later.

**Comment by constantinpape** [comment] 2021-11-07 10:45
Nifty available on conda-forge now.

**Closed by constantinpape** 2021-11-07 10:45 UTC
